create table if not exists public.visitors (
    id bigint generated by default as identity primary key,
    page text not null default '/',
    visited_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    customer_email text,
    package_type text not null default 'باقة مخصصة',
    details text not null default '',
    budget numeric,
    status text not null default 'new' check (status in ('new', 'contacted', 'completed', 'cancelled')),
    created_at timestamptz not null default now()
);

alter table public.visitors enable row level security;
alter table public.orders enable row level security;

drop policy if exists "public can record visits" on public.visitors;
create policy "public can record visits"
on public.visitors for insert
to anon, authenticated
with check (true);

drop policy if exists "owner can read visits" on public.visitors;
create policy "owner can read visits"
on public.visitors for select
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');

drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders"
on public.orders for insert
to anon, authenticated
with check (true);

drop policy if exists "owner can read orders" on public.orders;
create policy "owner can read orders"
on public.orders for select
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');

drop policy if exists "owner can update orders" on public.orders;
create policy "owner can update orders"
on public.orders for update
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mahmoud229sa@gmail.com');
